### ISSUE TITLE
How to enable bypassAuthorize?

### ISSUE THREAD

**Issue by mwkcoding** [devsrv/laravel-inplace#3]
How do you enable this? Your documentation is very confusing.

**Comment by devsrv** [comment]
this package is not ready yet, a lot work remaining, thanks for your interest :)

if you are defining field with Field maker (via class instead of blade component attribute then `->bypassAuthorize()` is available [check here](https://github.com/devsrv/laravel-inplace-example/blob/2225ee785f4369f970cedaa09578d29c08b91098/app/Http/Inplace/Text.php#L17)
this will skip all authorization checking & allow anyone to edit through the field

**Comment by mwkcoding** [comment]
I figured out how it works in the end and made it work. Thank you!
